"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 20:52:02.879257
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name')
    )
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('twitch', 'youtube', 'chzzk', name='platform', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('platform_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('offline', 'live', 'error', name='channel_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('live_title', sa.Text(), nullable=True),
    sa.Column('live_category', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_live_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_live_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_failures', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('default_game_id', sa.Integer(), nullable=True),
    sa.Column('default_tier_id', sa.Integer(), nullable=True),
    sa.Column('skip_stream_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_tier_id'], ['tiers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('recordings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('platform_stream_id', sa.String(length=128), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('recording', 'ending', 'finalizing', 'completed', 'failed', name='recording_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ending_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_polls', sa.Integer(), nullable=False),
    sa.Column('gcs_prefix', sa.Text(), nullable=False),
    sa.Column('quality', sa.String(length=32), nullable=True),
    sa.Column('bytes_recorded', sa.BigInteger(), nullable=False),
    sa.Column('chat_messages', sa.Integer(), nullable=False),
    sa.Column('chat_offset_s', sa.Float(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('labels_source', sa.Enum('manual', 'channel_default', 'suggested', name='labels_source', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tier_id'], ['tiers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recordings_status_started', 'recordings', ['status', 'started_at'], unique=False)
    op.create_table('chat_minutes',
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('messages', sa.Integer(), nullable=False),
    sa.Column('unique_chatters', sa.Integer(), nullable=False),
    sa.Column('paid_messages', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recording_id', 'minute')
    )
    op.create_table('segments',
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('video', 'chat', name='segment_kind', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('start_s', sa.Float(), nullable=True),
    sa.Column('end_s', sa.Float(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'uploading', 'uploaded', 'failed', name='segment_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recording_id', 'kind', 'seq')
    )
    op.create_index('ix_segments_pending', 'segments', ['next_attempt_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###

    # Starting labels. More tiers can be added from the label picker.
    op.execute("INSERT INTO games (name) VALUES ('WoW'), ('FFXIV')")
    op.execute(
        "INSERT INTO tiers (game_id, name, archived) "
        "SELECT id, 'Curse of U''latek', false FROM games WHERE name = 'WoW' "
        "UNION ALL SELECT id, 'Kefka Ultimate', false FROM games WHERE name = 'FFXIV'"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_segments_pending', table_name='segments', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('segments')
    op.drop_table('chat_minutes')
    op.drop_index('ix_recordings_status_started', table_name='recordings')
    op.drop_table('recordings')
    op.drop_table('channels')
    op.drop_table('tiers')
    op.drop_table('games')
    # ### end Alembic commands ###
